# Generated by Django 4.0.2 on 2022-02-23 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=130, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('slug', models.SlugField(max_length=130, verbose_name='Slug')),
                ('estudantes', models.ManyToManyField(through='app_cursos.Avaliacoes', to='app_cursos.Estudante')),
            ],
        ),
        migrations.AddField(
            model_name='avaliacoes',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cursos.cursos'),
        ),
        migrations.AddField(
            model_name='avaliacoes',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cursos.estudante'),
        ),
    ]
