# Generated by Django 4.0.2 on 2022-02-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacoes',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='cursos',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='estudante',
            options={'verbose_name': 'Estudante', 'verbose_name_plural': 'Estudantes'},
        ),
        migrations.AlterField(
            model_name='cursos',
            name='slug',
            field=models.SlugField(editable=False, max_length=130, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='slug',
            field=models.SlugField(editable=False, max_length=130, verbose_name='Slug'),
        ),
    ]
