# Generated by Django 4.0.2 on 2022-02-23 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cursos', '0002_alter_avaliacoes_options_alter_cursos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacoes',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='app_cursos.cursos'),
        ),
        migrations.AlterField(
            model_name='avaliacoes',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='app_cursos.estudante'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='estudantes',
            field=models.ManyToManyField(related_name='cursos', through='app_cursos.Avaliacoes', to='app_cursos.Estudante'),
        ),
    ]
